import plotly.io as pio
from fpdf import FPDF
import tempfile
import os


def export_dashboard_pdf(figures: list, filename="report.pdf") -> bytes:
    """
    Export a list of Plotly figures into a single PDF report.
    Returns: PDF bytes.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title Page
    pdf.add_page()
    pdf.set_font("Arial", 'B', 24)
    pdf.cell(200, 40, "Data Insights Report", ln=True, align='C')
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, "Auto-generated by Anti-Gravity AI Data Analyzer", ln=True, align='C')
    pdf.ln(20)

    # Process figures
    with tempfile.TemporaryDirectory() as tmp_dir:
        for i, fig in enumerate(figures):
            try:
                # Convert Plotly figure to static image (PNG)
                img_path = os.path.join(tmp_dir, f"fig_{i}.png")
                # Using scale for higher resolution
                pio.write_image(fig, img_path, format="png", scale=2, width=800, height=500)
                
                pdf.add_page()
                pdf.set_font("Arial", 'B', 16)
                title = fig.layout.title.text if fig.layout.title.text else f"Visualization {i+1}"
                pdf.cell(200, 10, title, ln=True, align='L')
                pdf.ln(10)
                
                # Add image to PDF. W=190 for approx full page width in A4
                pdf.image(img_path, x=10, y=pdf.get_y(), w=190)
                
            except Exception as e:
                pdf.add_page()
                pdf.set_font("Arial", 'I', 12)
                pdf.multi_cell(0, 10, f"Error rendering Visualization {i+1}: {str(e)}")
    
    return pdf.output()
